### ISSUE TITLE
Make the website working

### ISSUE THREAD

**Issue by avilas-nanda** [CareerDevelopmentHub/Resume-Generator#2]
The website is static, make it functioning.

**Comment by kaal-coder** [comment]
Can I do this ?

**Comment by avilas-nanda** [comment]
Yeah, you can !

**Comment by kaal-coder** [comment]
@avilas-nanda I have made the changes. Please have a look

**Comment by avilas-nanda** [comment]
Yeah. The work is as expected. Good one @kaal-coder
