### ISSUE TITLE
Make the add button functioning 

### ISSUE THREAD

**Issue by HarshDDalwadi** [CareerDevelopmentHub/Resume-Generator#4]
1> Add button is used to add as many Work experience section
2> Add button is used to add as many Education

**Comment by HarshDDalwadi** [comment]
Please assign me this issue, as I know to solve this using javaScript

**Comment by avilas-nanda** [comment]
This [issue is already there](https://github.com/CareerDevelopmentHub/Resume-Generator/issues/2). Elaborate how you want to do there
